-- Esquema inicial: refleja las entidades JPA tras el refactor a capas.
-- Las migraciones ya aplicadas NO se editan: cualquier cambio va en un V2, V3...

-- ───── Usuarios ─────

create table users (
    id            bigint generated by default as identity primary key,
    username      varchar(50)  not null,
    email         varchar(200) not null,
    password_hash varchar(100) not null,
    display_name  varchar(100) not null,
    role          varchar(20)  not null check (role in ('ADMIN', 'STUDENT')),
    active        boolean      not null,
    created_at    timestamp(6) not null,
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email)
);

-- ───── Banco de preguntas ─────

create table tags (
    id         bigint generated by default as identity primary key,
    name       varchar(50)  not null,
    color      varchar(7)   not null,
    owner_id   bigint       not null references users (id),
    created_at timestamp(6) not null,
    constraint uk_tags_name_owner unique (name, owner_id)
);
create index idx_tags_owner on tags (owner_id);

create table questions (
    id             bigint generated by default as identity primary key,
    text           varchar(1000) not null,
    correct_answer integer       not null,
    explanation    varchar(2000),
    difficulty     varchar(20)   not null check (difficulty in ('FACIL', 'MEDIO', 'DIFICIL')),
    owner_id       bigint        not null references users (id),
    created_at     timestamp(6)  not null,
    updated_at     timestamp(6)  not null
);
create index idx_questions_owner on questions (owner_id);

create table question_options (
    question_id  bigint       not null references questions (id) on delete cascade,
    option_order integer      not null,
    option_text  varchar(500) not null,
    primary key (question_id, option_order)
);

create table question_tags (
    question_id bigint not null references questions (id) on delete cascade,
    tag_id      bigint not null references tags (id),
    primary key (question_id, tag_id)
);

-- ───── Exámenes ─────

create table exams (
    id                       bigint generated by default as identity primary key,
    title                    varchar(200) not null,
    owner_id                 bigint       not null references users (id),
    status                   varchar(20)  not null check (status in ('DRAFT', 'PUBLISHED', 'EXPIRED')),
    visibility               varchar(20)  not null check (visibility in ('PRIVATE', 'PUBLIC')),
    access_mode              varchar(20)  not null check (access_mode in ('OPEN', 'REGISTERED_ONLY')),
    number_of_questions      integer      not null,
    time_limit_minutes       integer,
    show_score               boolean      not null,
    randomize_options        boolean      not null,
    randomize_question_order boolean      not null,
    code                     varchar(50),
    created_at               timestamp(6) not null,
    expires_at               timestamp(6),
    constraint uk_exams_code unique (code)
);
create index idx_exams_owner on exams (owner_id);

-- Preguntas de cada examen, en orden
create table exam_questions (
    exam_id     bigint  not null references exams (id) on delete cascade,
    position    integer not null,
    question_id bigint  not null references questions (id),
    primary key (exam_id, position)
);
create index idx_exam_questions_question on exam_questions (question_id);

-- Tags usados al pre-generar un examen (informativo)
create table exam_generation_tags (
    exam_id bigint not null references exams (id) on delete cascade,
    tag_id  bigint not null references tags (id),
    primary key (exam_id, tag_id)
);

create table exam_favorites (
    id           bigint generated by default as identity primary key,
    professor_id bigint       not null references users (id),
    exam_id      bigint       not null references exams (id) on delete cascade,
    created_at   timestamp(6) not null,
    constraint uk_favorites_professor_exam unique (professor_id, exam_id)
);

-- ───── Resultados ─────

create table results (
    id                 bigint generated by default as identity primary key,
    exam_id            bigint       not null references exams (id),
    student_user_id    bigint       references users (id),
    student_name       varchar(100) not null,
    student_club       varchar(100),
    student_email      varchar(200),
    correct_answers    integer      not null,
    total_questions    integer      not null,
    score              integer      not null,
    time_spent_seconds integer      not null,
    completed_at       timestamp(6) not null
);
create index idx_results_exam on results (exam_id);
create index idx_results_student on results (student_user_id);

-- Respuestas de cada entrega. question_id sin clave foránea: el resultado
-- guarda la respuesta correcta del momento y no depende de la pregunta viva.
create table result_answers (
    result_id      bigint  not null references results (id) on delete cascade,
    position       integer not null,
    question_id    bigint  not null,
    student_answer integer,
    correct_answer integer not null,
    primary key (result_id, position)
);
